services:
  todolist_back:
    build: .
    ports:
      - 3333:3333
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: todolist_psql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist_back
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
